<?php
namespace App\Controller\Component;

use Cake\Controller\Component;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\IOFactory;

use Cake\I18n\Time;

class ExportFileComponent extends Component
{

    public function setXlsxProperties()
    {
        // Create new Spreadsheet object
        $spreadsheet = new Spreadsheet();

        // Set document properties
        $spreadsheet->getProperties()->setCreator('Tâm Việt')
            ->setLastModifiedBy('Tâm Việt')
            ->setTitle('Office 2007 XLSX Document')
            ->setSubject('Office 2007 XLSX Document')
            ->setDescription('Document for Office 2007 XLSX, generated by Tâm Việt.')
            ->setKeywords('office 2007 openxml php')
            ->setCategory('Result file');
        
        return $spreadsheet;
    }

    public function generateFooter($spreadsheet, $row, $col)
    {
        $now = Time::now();
        $day = str_pad((string) $now->day, 2, '0', STR_PAD_LEFT);
        $month = str_pad((string) $now->month, 2, '0', STR_PAD_LEFT);
        $spreadsheet->getActiveSheet()->mergeCells('A'.$row.':'.$col.$row)
            ->setCellValue('A'.$row, 'TPHCM, ngày ' . $day . ' tháng ' . $month . ' năm ' . $now->year);
        $spreadsheet->getActiveSheet()->getStyle('A'.$row)->getFont()->setItalic(true);
        $spreadsheet->getActiveSheet()->getStyle('A'.$row)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_RIGHT);
        return $spreadsheet;
    }

    public function export($spreadsheet, $filename)
    {
        // Redirect output to a client’s web browser (Xlsx)
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="'. $filename .'"');
        header('Cache-Control: max-age=0');
        // If you're serving to IE 9, then the following may be needed
        header('Cache-Control: max-age=1');

        // If you're serving to IE over SSL, then the following may be needed
        header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
        header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
        header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
        header('Pragma: public'); // HTTP/1.0

        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $writer->save('php://output');
    }
}